language: java
jdk:
- openjdk11
- openjdk14

git:
  depth: false

addons:
  sonarcloud:
    organization: "justifiedsolutions"
    token: 
      secure: "uHUI91RSnZlIcxqhsA+iVR6IfN7vVtGoEoHrTOB8dsEL6XfR/2FoOZpn6Oew13jGOvFVBLO6MIrc90tFh9nG++4pZ/jpwmNSEXlFdRVY/Ju4lQEJwIOAlRQZidpDvxhcpqXhCSdXj+sTN6Ylt2GHmv7jxbse9bgwyyvYLXQnm6LhDhN5qkGCmpzcHZ/IrZziOWhGZ2XuDOwfyulyUln4x3UOrU+cjS7FMeFx7JF9wFmumE3HB55NWOf9uTh8efP/kncLuw2Dz5eNwMdW5KSfXkT6sK7lCh/I0uBgY47MvftWk1S5AA9Hq3409Z/60CAKjFhQN8AO3EFTKtxxLJ9IQqhs2AvDi+Q27WLMobwDjpq6mns3PAIhdJPJhlwFMy6DfZ3j08Tb+vnIpqI9Kq4P/cJZR5Mk5bH4SZ/j6EHqq+JeoCKpUAiAXuCimgPMju0C9d/v7YsFDHg98VntaOFC/3SnhGECUjvVhDudQq0PJDk+e5pI7wgrbh8J3z9mNaSWFnEvQVa9R3GRRDpIv+Q9ZCmIkl2BfhQn4MZXoZsCiDqR0R8h58be/OZZKmdw+YgZU83+HWlAXLrKpl84s7bIsbD6u0ksY3Lxt2IyEhYeR6albDblNLM4KSNN/zacvSYAHQhHJypxogBpFwp6fT1fe9GiX+P79k18k+Z88Ax7EGg="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar
