version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    docker:
      - image: adoptopenjdk:11-jdk-hotspot-focal
    resource_class: small
    steps:
      - maven/test

workflows:
  maven_test:
    jobs:
      - build

