version: 2.1

executors:
  jdk11:
    docker:
      - image: 'cimg/openjdk:11.0'
  jdk15:
    docker:
      - image: 'cimg/openjdk:15.0'

orbs:
  maven: circleci/maven@1.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 'verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=justifiedsolutions -Dsonar.projectKey=com.justifiedsolutions:justPDF'
          matrix:
            parameters:
              executor:
                - jdk11
                - jdk15

