version: 2.1

executors:
  jdk11:
    docker:
      - image: 'cimg/openjdk:11.0'
    resource_class: small

orbs:
  maven: circleci/maven@1.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          context: sonarcloud
          command: 'verify sonar:sonar'
          executor: jdk11
