name: 'Deploy'
on:
  release:
    types: published
  workflow_dispatch:
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Install GPG'
        run: |
          sudo apt-get update
          sudo apt-get install gpg
      - name: 'Configure GPG'
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        run: |
          echo ${GPG_SIGNING_KEY} | gpg --batch --no-tty --import --yes
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: 'Maven Deploy'
        env:
          GPG_PASS: ${{ secrets.GPG_PASS }}
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          mvn \
          -s ./maven-release-settings.xml \
          clean deploy \
          -DskipTests=true \
          -Dpmd.skip=true \
          -Djacoco.skip=true \
          -Dgpg.passphrase=${GPG_PASS} \
          -Prelease

