name: Validate
on: push

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  run-tests:
    name: 'Validate'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup Java'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: 'Maven Verify'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: 'mvn --batch-mode --update-snapshots --no-transfer-progress verify sonar:sonar'

      - name: 'Publish Test Results'
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'target/surefire-reports/TEST-*.xml'
